Modules/System/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'middleware' => 'auth',
    'as' => 'dashboard.'
], function() {
    Route::get('/', 'SystemController@index')->name('index');
});

Modules/System/Http/Controllers/SystemController.php
<?php

namespace Modules\System\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class SystemController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('system::index', [
            'title' => __('Dashboard'),
            'subtitle' => null,
            'breadcrumb' => [
                [
                    'title' => __('Dashboard'),
                    'current' => true,
                    'icon' => 'mdi mdi-view-dashboard'
                ]
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('system::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('system::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit()
    {
        return view('system::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request)
    {
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy()
    {
    }
}

Modules/System/Resources/views/partials/aside.blade.php
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                @foreach(config('system.menu') as $key => $item)
                    @if(is_check($item['param'], $item['check']))
                        @if($item['type'] == 'link')
                            <li class="sidebar-item {{ in_route($key) ? 'selected' : '' }}">
                                <a class="sidebar-link waves-effect waves-dark sidebar-link {{ in_route($key) ? 'active' : '' }}" href="{{ get_route($item['route']) }}" aria-expanded="false">
                                    <i class="{{ $item['icon'] }}"></i><span class="hide-menu">{{ $item['text'] }}</span>
                                </a>
                            </li>
                        @elseif($item['type'] == 'items')
                            <li class="sidebar-item {{ in_route($key) ? 'selected' : '' }}">
                                <a class="sidebar-link has-arrow waves-effect waves-dark {{ in_route($key) ? 'active' : '' }}" href="javascript:void(0)" aria-expanded="false">
                                    <i class="{{ $item['icon'] }}"></i><span class="hide-menu">{{ $item['text'] }}</span>
                                </a>
                                <ul aria-expanded="false" class="collapse first-level  {{ in_route($key) ? 'in' : '' }}">
                                    @foreach($item['items'] as $subKey => $subItem)
                                        @if(is_check($subItem['param'], $subItem['check']))
                                            <li class="sidebar-item">
                                                <a href="{{ get_route($subItem['route']) }}" class="sidebar-link">
                                                    <i class="{{ $subItem['icon'] }}"></i><span class="hide-menu">{{ $subItem['text'] }}</span>
                                                </a>
                                            </li>
                                        @endif
                                    @endforeach
                                </ul>
                            </li>
                        @endif
                    @endif
                @endforeach
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->

Modules/System/Resources/views/partials/footer.blade.php
<!-- footer -->
<!-- ============================================================== -->
<footer class="footer main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <p>@ {{ date('Y') }} | <a href="https://intercet.com.br">{{ strtoupper(config('developer.business.name')) }}</a></p>
            </div>
            <div class="col-xs-12 col-md-6 text-right">
                <ul>
                    <li><a href="{{ config('developer.url.support') }}">{{ __('Support') }}</a></li>
                    <li><a href="{{ config('developer.url.contact') }}">{{ __('Contact') }}</a></li>
                    <li><a href="{{ config('developer.url.faq') }}">{{ __('FAQ') }}</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- ============================================================== -->
<!-- End footer -->
<!-- ============================================================== -->

Modules/System/Resources/views/partials/header.blade.php
<!-- ============================================================== -->
<!-- Topbar header - style you can find in pages.scss -->
<!-- ============================================================== -->
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{{ route('dashboard.index') }}">

                <!-- Logo text -->
                <span class="logo-text">
                     <!-- dark Logo text -->
                     <img src="{{ asset('images/logotipo.svg')}}" alt="homepage" class="light-logo" style="width: auto;height:50px;" />
                </span>
                <b class="logo-icon">
                    <img src="{{ asset('images/logo.svg') }}" alt="homepage" class="light-logo" style="height: 50px; widows: auto;" />
                </b>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                <!-- ============================================================== -->
                <!-- create new -->
                <!-- ============================================================== -->

            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="mdi mdi-bell font-24"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="font-24 mdi mdi-comment-processing"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="">
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-success btn-circle"><i class="ti-calendar"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Event today</h5>
                                                <span class="mail-desc">Just a reminder that event</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-info btn-circle"><i class="ti-settings"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Settings</h5>
                                                <span class="mail-desc">You can customize this template</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-primary btn-circle"><i class="ti-user"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Pavan kumar</h5>
                                                <span class="mail-desc">Just see the my admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-danger btn-circle"><i class="fa fa-link"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Luanch Admin</h5>
                                                <span class="mail-desc">Just see the my new admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->

                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="../../assets/images/users/1.jpg" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated">
                        <a class="dropdown-item" href="{{ get_route('profile.index')  }}"><i class="ti-user m-r-5 m-l-5"></i> Meu Perfil</a>
                        {{--<a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i> Meu Departamento</a>--}}
                        <a class="dropdown-item" href="{{ url('sair') }}"><i class="fa fa-power-off m-r-5 m-l-5"></i> Sair</a>

                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->

Modules/System/Resources/views/partials/scripts.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('components/jquery-ui/jquery-ui.min.js') }}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
    window.paceOptions = {
        ajax: {
            trackMethods: ['GET', 'POST', 'PUT', 'DELETE', 'REMOVE']
        }
    };
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
            'X-USER-TOKEN': $('meta[name="user-reference"]').attr('content'),
            'X-Requested-With': 'XMLHttpRequest',
        }
    });
</script>
<script src="{{ asset('assets/libs/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{ asset('assets/libs/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js')}}"></script>
<script src="{{ asset('assets/extra-libs/sparkline/sparkline.js')}}"></script>
<script src="{{ asset('assets/js/waves.js')}}"></script>
<script src="{{ asset('assets/js/sidebarmenu.js')}}"></script>
<script src="{{ asset('assets/js/custom.min.js')}}"></script>
<script src="{{ asset('assets/libs/toastr/build/toastr.min.js')}}"></script>
<!--This page JavaScript -->
<!-- <script src="../../dist/js/pages/dashboards/dashboard1.js"></script> -->
<!-- Charts js Files -->
<script src="{{ asset('assets/libs/flot/excanvas.js')}}"></script>
<script src="{{ asset('assets/libs/flot/jquery.flot.js')}}"></script>
<script src="{{ asset('assets/libs/flot/jquery.flot.pie.js')}}"></script>
<script src="{{ asset('assets/libs/flot/jquery.flot.time.js')}}"></script>
<script src="{{ asset('assets/libs/flot/jquery.flot.stack.js')}}"></script>
<script src="{{ asset('assets/libs/flot/jquery.flot.crosshair.js')}}"></script>
<script src="{{ asset('assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{ asset('assets/js/pages/chart/chart-page-init.js')}}"></script>
<script src="{{ asset('js/system.min.js')}}"></script>
<script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-center",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "500",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    @if(session('status'))
        toastr['{{session("status")}}']("{{session('msg')}}");
    @endif



</script>

Modules/System/Resources/views/partials/styles.blade.php
<!-- Custom CSS -->
<link href="{{ asset('assets/libs/flot/css/float-chart.css')}}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{{ asset('assets/css/style.min.css')}}" rel="stylesheet">
<link href="{{ asset('assets/css/custom.css')}}" rel="stylesheet">
<link href="{{ asset('css/app.min.css')}}" rel="stylesheet">
<link href="{{ asset('assets/libs/snackbar/css/style.css')}}" rel="stylesheet">
<!-- Toastr CSS -->
<link href="{{ asset('assets/libs/toastr/build/toastr.min.css')}}" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

Modules/System/Resources/views/partials/subheader.blade.php
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">
                {{ $title or '' }}
                @isset($subtitle)
                    <small>{{ $subtitle }}</small>
                @endisset

                <span class="push-buttons" style="margin-left: 15px;">
                    @stack('push-buttons')
                </span>
            </h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @foreach($breadcrumb as $key => $item)
                            @if($item['current'])
                                <li class="breadcrumb-item active" aria-current="page">@isset($item['icon'])<i class="{{ $item['icon'] }}"></i>@endisset {{ $item['title'] }}</li>
                            @else
                                <li class="breadcrumb-item">
                                    <a href="{{ $item['url'] }}">
                                        @isset($item['icon'])<i class="{{ $item['icon'] }}"></i>@endisset {{ $item['title'] }}
                                    </a>
                                </li>
                            @endif
                        @endforeach
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

@if($errors->any() or session()->has('fail') or session()->has('success'))
    <div class="container-fluid" style="min-height: auto; padding-bottom: 0;">
        @if ($errors->any())
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger" style="margin-bottom: 0;">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
        @if(session()->has('fail'))
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger" style="margin-bottom: 0;">
                        <span>{{ session()->get('fail') }}</span>
                    </div>
                </div>
            </div>
        @endif
        @if(session()->has('success'))
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success" style="margin-bottom: 0;">
                        <span>{{ session()->get('success') }}</span>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endif